import { ITier, IMilestone } from '@/types/expedition';

// ============================================
// Tier 1 - Onchain Initiate
// ============================================
const onchain_initiate_milestones: IMilestone[] = [
  {
    id: 'mn_t1_m1',
    name: 'Deposit $100+',
    description: 'Deposit at least $100 into your wallet to start trading.',
    actionType: 'wallet_deposit',
    points: 20,
    completed: false,
    requirement: { amount: 100 },
    link: { url: '/portfolio', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Deposit',
  },
  {
    id: 'mn_t1_m2',
    name: 'Make a Perp Trade',
    description: 'Place your first Perpetual Futures trade.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t1_m3',
    name: 'Follow Hotstuff on X',
    description: 'Follow Hotstuff on X to receive updates and announcements.',
    actionType: 'follow_on_x',
    points: 20,
    completed: false,
    link: {
      url: 'https://x.com/intent/follow?screen_name=tradehotstuff',
      target: '_blank',
      type: 'metadata',
      metadata: { twitter_follow: true },
    },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Follow',
  },
  {
    id: 'mn_t1_m4',
    name: 'Join Discord',
    description: 'Join the Hotstuff Discord to connect with other traders.',
    actionType: 'join_discord',
    points: 20,
    completed: false,
    link: {
      url: 'https://discord.gg/tradehotstuff',
      target: '_blank',
      type: 'metadata',
      metadata: { discord_join: true },
    },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Join',
  },
  {
    id: 'mn_t1_m5',
    name: 'Deposit $10+ to HLV',
    description: 'Deposit at least $10 into the Hotstuff Liquidity Vault.',
    actionType: 'vault_deposit',
    points: 20,
    completed: false,
    requirement: { amount: 10 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Vaults',
  },
];

// ============================================
// Tier 2 - Market Explorer
// ============================================
const market_explorer_milestones: IMilestone[] = [
  {
    id: 'mn_t2_m1',
    name: '3-Day GM Streak',
    description: 'Maintain a 3-day GM streak to unlock this milestone.',
    actionType: 'collect_streaks',
    points: 20,
    completed: false,
    requirement: { count: 3 },
    link: { url: '/portfolio', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Claim GM',
  },
  {
    id: 'mn_t2_m2',
    name: '3-Day Trading Streak',
    description: 'Trade on 3 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 3 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t2_m3',
    name: 'Trade 2 Markets',
    description: 'Trade in at least 2 different markets.',
    actionType: 'different_markets',
    points: 20,
    completed: false,
    requirement: { count: 2 },
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t2_m4',
    name: '$10K Cumulative Volume',
    description: 'Reach $10,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 10000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t2_m5',
    name: 'Refer 2 Traders',
    description: 'Refer 2 active traders to Hotstuff.',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 2 },
    action: 'create-referral-code',
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Invite',
  },
];

// ============================================
// Tier 3 - Leverage Specialist
// ============================================
const leverage_specialist_milestones: IMilestone[] = [
  {
    id: 'mn_t3_m1',
    name: '5-Day Trading Streak',
    description: 'Trade on 5 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 5 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t3_m2',
    name: '5-Day GM Streak',
    description: 'Maintain a 5-day GM streak.',
    actionType: 'collect_streaks',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    link: { url: '/portfolio', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Claim GM',
  },
  {
    id: 'mn_t3_m3',
    name: '$100K Cumulative Volume',
    description: 'Reach $100,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 100000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t3_m4',
    name: 'Trade Altcoin Perp',
    description: 'Trade at least one altcoin perpetual (non-BTC/ETH).',
    actionType: 'altcoin_perp_trade',
    points: 20,
    completed: false,
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t3_m5',
    name: 'Deposit $500+ to HLV',
    description: 'Deposit at least $500 into the Hotstuff Liquidity Vault.',
    actionType: 'vault_deposit',
    points: 20,
    completed: false,
    requirement: { amount: 500 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Vaults',
  },
];

// ============================================
// Tier 4 - Liquidity Vanguard
// ============================================
const liquidity_vanguard_milestones: IMilestone[] = [
  {
    id: 'mn_t4_m1',
    name: '7-Day Trading Streak',
    description: 'Trade on 7 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 7 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t4_m2',
    name: 'Trade on 7+ Unique Days',
    description: 'Trade on at least 7 different days (not necessarily consecutive).',
    actionType: 'unique_trading_days',
    points: 20,
    completed: false,
    requirement: { days: 7 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t4_m3',
    name: '$500K Cumulative Volume',
    description: 'Reach $500,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 500000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t4_m4',
    name: 'Trade 3 Markets',
    description: 'Trade in at least 3 different markets.',
    actionType: 'different_markets',
    points: 20,
    completed: false,
    requirement: { count: 3 },
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t4_m5',
    name: 'Refer 5 Traders',
    description: 'Refer 5 active traders to Hotstuff.',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    action: 'create-referral-code',
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Invite',
  },
];

// ============================================
// Tier 5 - Market Architect
// ============================================
const market_architect_milestones: IMilestone[] = [
  {
    id: 'mn_t5_m1',
    name: '10-Day Trading Streak',
    description: 'Trade on 10 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 10 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t5_m2',
    name: '$1M+ Cumulative Volume',
    description: 'Reach $1,000,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 1000000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t5_m3',
    name: 'Trade 5 Markets',
    description: 'Trade in at least 5 different markets.',
    actionType: 'different_markets',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t5_m4',
    name: 'HLV Deposit 7+ Days',
    description: 'Maintain HLV deposit for at least 7 days.',
    actionType: 'hlv_deposit_duration',
    points: 20,
    completed: false,
    requirement: { days: 7 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Vaults',
  },
  {
    id: 'mn_t5_m5',
    name: 'Refer 10 Traders',
    description: 'Refer 10 active traders to Hotstuff.',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 10 },
    action: 'create-referral-code',
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Invite',
  },
];

// ============================================
// Tier 6 - Flow Commander
// ============================================
const flow_commander_milestones: IMilestone[] = [
  {
    id: 'mn_t6_m1',
    name: '14-Day Trading Streak',
    description: 'Trade on 14 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 14 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t6_m2',
    name: '$3M+ Cumulative Volume',
    description: 'Reach $3,000,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 3000000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t6_m3',
    name: 'Trade 8 Markets',
    description: 'Trade in at least 8 different markets.',
    actionType: 'different_markets',
    points: 20,
    completed: false,
    requirement: { count: 8 },
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t6_m4',
    name: 'HLV Deposit 14+ Days',
    description: 'Maintain HLV deposit for at least 14 days.',
    actionType: 'hlv_deposit_duration',
    points: 20,
    completed: false,
    requirement: { days: 14 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Vaults',
  },
  {
    id: 'mn_t6_m5',
    name: 'Refer 20 Traders',
    description: 'Refer 20 active traders to Hotstuff.',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 20 },
    action: 'create-referral-code',
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Invite',
  },
];

// ============================================
// Tier 7 - Market Sovereign
// ============================================
const market_sovereign_milestones: IMilestone[] = [
  {
    id: 'mn_t7_m1',
    name: '21-Day Trading Streak',
    description: 'Trade on 21 consecutive days.',
    actionType: 'trading_streak',
    points: 20,
    completed: false,
    requirement: { days: 21 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t7_m2',
    name: '$10M+ Cumulative Volume',
    description: 'Reach $10,000,000 in cumulative perp trading volume.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 10000000 },
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t7_m3',
    name: 'Trade 10+ Markets',
    description: 'Trade in at least 10 different markets.',
    actionType: 'different_markets',
    points: 20,
    completed: false,
    requirement: { count: 10 },
    link: { url: '/trade', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 'mn_t7_m4',
    name: 'HLV Deposit 30+ Days',
    description: 'Maintain HLV deposit for at least 30 days.',
    actionType: 'hlv_deposit_duration',
    points: 20,
    completed: false,
    requirement: { days: 30 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Vaults',
  },
  {
    id: 'mn_t7_m5',
    name: 'Refer 30 Traders',
    description: 'Refer 30 active traders to Hotstuff.',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 30 },
    action: 'create-referral-code',
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Invite',
  },
];

// ============================================
// Mainnet Expedition Tiers Export
// ============================================

export const MAINNET_EXPEDITION_TIERS: ITier[] = [
  {
    id: 0,
    name: 'Onchain Initiate',
    title: 'Tier 1 - Onchain Initiate',
    description: 'Begin your trading journey. Make your first deposit and trade.',
    milestones: onchain_initiate_milestones,
    totalPoints: onchain_initiate_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/onchain_initiate.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/onchain_initiate_bg.svg',
    borderGradient: 'linear-gradient(180deg, #FACE8D 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/onchain_initiate.svg',
    unlocked: true,
  },
  {
    id: 1,
    name: 'Market Explorer',
    title: 'Tier 2 - Market Explorer',
    description: 'Explore different markets and build your trading streak.',
    milestones: market_explorer_milestones,
    totalPoints: market_explorer_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/market_explorer.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/market_explorer_bg.svg',
    borderGradient: 'linear-gradient(180deg, #D57E8B 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/market_explorer.svg',
    unlocked: true,
  },
  {
    id: 2,
    name: 'Leverage Specialist',
    title: 'Tier 3 - Leverage Specialist',
    description: 'Master leverage trading and grow your volume.',
    milestones: leverage_specialist_milestones,
    totalPoints: leverage_specialist_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/leverage_specialist.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/leverage_specialist_bg.svg',
    borderGradient: 'linear-gradient(180deg, #8BE1F3 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/leverage_specialist.svg',
    unlocked: true,
  },
  {
    id: 3,
    name: 'Liquidity Vanguard',
    title: 'Tier 4 - Liquidity Vanguard',
    description: 'Lead the charge in providing liquidity and trading activity.',
    milestones: liquidity_vanguard_milestones,
    totalPoints: liquidity_vanguard_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/liquidity_vanguard.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/liquidity_vanguard_bg.svg',
    borderGradient: 'linear-gradient(180deg, #B6ABFF 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/liquidity_vanguard.svg',
    unlocked: true,
  },
  {
    id: 4,
    name: 'Market Architect',
    title: 'Tier 5 - Market Architect',
    description: 'Shape the market with significant trading volume and influence.',
    milestones: market_architect_milestones,
    totalPoints: market_architect_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/market_architect.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/market_architect_bg.svg',
    borderGradient: 'linear-gradient(180deg, #D57E8B 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/market_architect.svg',
    unlocked: true,
  },
  {
    id: 5,
    name: 'Flow Commander',
    title: 'Tier 6 - Flow Commander',
    description: 'Command the flow of markets with elite trading performance.',
    milestones: flow_commander_milestones,
    totalPoints: flow_commander_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/flow_commander.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/flow_commander_bg.svg',
    borderGradient: 'linear-gradient(180deg, #F8AAFA 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/flow_commander.svg',
    unlocked: true,
  },
  {
    id: 6,
    name: 'Market Sovereign',
    title: 'Tier 7 - Market Sovereign',
    description: 'Reign supreme as a legendary market participant.',
    milestones: market_sovereign_milestones,
    totalPoints: market_sovereign_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/mainnet/market_sovereign.svg',
    badgeBackground: '/imgs/png/expedition/mainnet/market_sovereign_bg.svg',
    borderGradient: 'linear-gradient(180deg, #CDF0AD 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/mainnet/market_sovereign.svg',
    unlocked: true,
  },
];

export const TESTNET_OG = {
  id: -1,
  name: 'Testnet OG',
  title: 'Testnet OG',
  description: 'Joined Hotstuff on testnet.',
  milestones: [],
  totalPoints: 0,
  badgeIcon: '/imgs/png/expedition/mainnet/testnet_og.svg',
  badgeBackground: '/imgs/png/expedition/mainnet/testnet_og_bg.svg',
  borderGradient: 'linear-gradient(180deg, #DDDDDD 0%, #2E2E2B 100%)',
  tagIcon: '/imgs/png/expedition/mainnet/testnet_og.svg',
  unlocked: true,
};