import { ITier, IMilestone } from '@/types/expedition';

const rookie_hunter_milestones: IMilestone[] = [
  {
    id: 't1_m1',
    name: 'Claim Faucet',
    description: 'Get your first free funds to start using the platform.',
    actionType: 'claim_faucet',
    points: 20,
    completed: false,
    action: 'faucet',
    icon: './imgs/svg/expedition/mile_1.svg',
    actionText: 'Claim',
  },
  {
    id: 't1_m2',
    name: 'Make a Perp Trade',
    description: 'Place your first Perpetual Futures trade.',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    link: { url: '/trade/BTC-PERP', target: '_self' },
    icon: './imgs/svg/expedition/mile_2.svg',
    actionText: 'Trade',
  },
  {
    id: 't1_m3',
    name: 'Make a Spot Trade',
    description: 'Complete your first Spot market trade.',
    actionType: 'spot_trade',
    points: 20,
    completed: false,
    link: { url: '/trade/USDT/USDC', target: '_self' },
    icon: './imgs/svg/expedition/mile_3.svg',
    actionText: 'Trade',
  },
  {
    id: 't1_m4',
    name: 'Follow Hotstuff on X',
    description: 'Follow Hotstuff on X to receive updates and announcements.',
    actionType: 'follow_on_x',
    points: 20,
    completed: false,
    link: {
      url: 'https://x.com/intent/follow?screen_name=tradehotstuff',
      target: '_blank',
      type: 'metadata',
      metadata: { twitter_follow: true },
    },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Follow',
  },
  {
    id: 't1_m5',
    name: 'Deposit $100 to HLV',
    description: 'Deposit $100 into the Hotstuff Liquidity Vault (HLV).',
    actionType: 'deposit',
    points: 20,
    completed: false,
    requirement: { amount: 100 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Vaults',
  },
];

const funding_farmer_milestones: IMilestone[] = [
  {
    id: 't2_m1',
    name: 'Collect 5 GMs',
    description: 'Collect 5 GMs to unlock this milestone',
    actionType: 'collect_gms',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    icon: './imgs/svg/expedition/mile_1.svg',
    link: { url: '/portfolio', target: '_self' },
    actionText: 'Collect GMs',
  },
  {
    id: 't2_m2',
    name: 'Trade $100K Perp Volume',
    description: 'Trade $100,000 in perpetual trading volume',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 100000 },
    icon: './imgs/svg/expedition/mile_2.svg',
    link: { url: '/trade/BTC-PERP', target: '_self' },
    actionText: 'Trade',
  },
  {
    id: 't2_m3',
    name: 'Refer 2 Users',
    description: 'Refer 2 users to join Hotstuff',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 2 },
    icon: './imgs/svg/expedition/mile_3.svg',
    action: 'create-referral-code',
    actionText: 'Invite Friends',
  },
  {
    id: 't2_m4',
    name: 'Join Discord',
    description: 'Join the Hotstuff Discord to connect with other traders',
    actionType: 'join_discord',
    points: 20,
    completed: false,
    link: {
      url: 'https://discord.gg/tradehotstuff',
      target: '_blank',
      type: 'metadata',
      metadata: { discord_join: true },
    },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Join Community',
  },
  {
    id: 't2_m5',
    name: 'Repost & Like a Hotstuff Post',
    description: 'Repost & Like a Hotstuff Post to unlock this milestone',
    actionType: 'repost_post',
    points: 20,
    completed: false,
    link: {
      url: 'https://x.com/intent/retweet?tweet_id=1996952072219242828',
      target: '_blank',
      type: 'metadata',
      metadata: { twitter_engagement: true },
    },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Like and Repost',
  },
];

const leverage_pilot_milestones: IMilestone[] = [
  {
    id: 't3_m1',
    name: 'Complete 5 Streaks',
    description: 'Complete 5 Streaks to unlock this milestone',
    actionType: 'collect_streaks',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    icon: './imgs/svg/expedition/mile_1.svg',
    link: { url: '/portfolio', target: '_self' },
    actionText: 'Complete Streaks',
  },
  {
    id: 't3_m2',
    name: 'Unlock VIP2 Fee Tier',
    description: 'Trade $5M in trading volume',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 5000000 },
    icon: './imgs/svg/expedition/mile_2.svg',
    link: { url: '/trade/BTC-PERP', target: '_self' },
    actionText: 'Trade',
  },
  {
    id: 't3_m3',
    name: 'Refer 10 Users',
    description: 'Refer 10 users to join Hotstuff',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 10 },
    icon: './imgs/svg/expedition/mile_3.svg',
    link: { url: '/referrals', target: '_self' },
    actionText: 'Invite Friends',
  },
  {
    id: 't3_m4',
    name: 'Claim Referral Rewards',
    description: 'Claim your referral rewards to unlock this milestone',
    actionType: 'claim_referral_rewards',
    points: 20,
    completed: false,
    icon: './imgs/svg/expedition/mile_4.svg',
    link: { url: '/referrals', target: '_self' },
    actionText: 'Claim Rewards',
  },
  {
    id: 't3_m5',
    name: 'Deposit $1k to HLV',
    description: 'Deposit $1,000 into the Hotstuff Liquidity Vault (HLV).',
    actionType: 'deposit',
    points: 20,
    completed: false,
    requirement: { amount: 1000 },
    link: { url: '/vaults', target: '_self' },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Vaults',
  },
];

const volatility_surfer_milestones: IMilestone[] = [
  {
    id: 't4_m1',
    name: 'Collect 5 Streaks',
    description: 'Collect 5 Streaks to unlock this milestone',
    actionType: 'collect_streaks',
    points: 20,
    completed: false,
    requirement: { count: 5 },
    icon: './imgs/svg/expedition/mile_1.svg',
    link: { url: '/portfolio', target: '_self' },
    actionText: 'Collect Streaks',
  },
  {
    id: 't4_m2',
    name: 'Trade $100K Perp Volume',
    description: 'Trade $100,000 in perpetual trading volume',
    actionType: 'perp_trade',
    points: 20,
    completed: false,
    requirement: { volume: 100000 },
    icon: './imgs/svg/expedition/mile_2.svg',
    link: { url: '/trade/BTC-PERP', target: '_self' },
    actionText: 'Trade',
  },
  {
    id: 't4_m3',
    name: 'Refer 2 Users',
    description: 'Refer 2 users to join Hotstuff',
    actionType: 'refer_users',
    points: 20,
    completed: false,
    requirement: { count: 2 },
    icon: './imgs/svg/expedition/mile_3.svg',
    action: 'create-referral-code',
    actionText: 'Invite Friends',
  },
  {
    id: 't4_m4',
    name: 'Join Discord',
    description: 'Join the Hotstuff Discord to connect with other traders',
    actionType: 'join_discord',
    points: 20,
    completed: false,
    link: {
      url: 'https://discord.gg/tradehotstuff',
      target: '_blank',
      type: 'metadata',
      metadata: { discord_join: true },
    },
    icon: './imgs/svg/expedition/mile_4.svg',
    actionText: 'Join Community',
  },
  {
    id: 't4_m5',
    name: 'Repost a Hotstuff Post',
    description: 'Repost a Hotstuff Post to unlock this milestone',
    actionType: 'repost_post',
    points: 20,
    completed: false,
    link: {
      url: 'https://x.com/intent/retweet?tweet_id=1996952072219242828',
      target: '_blank',
      type: 'metadata',
      metadata: { twitter_engagement: true },
    },
    icon: './imgs/svg/expedition/mile_5.svg',
    actionText: 'Like and Repost',
  },
];

export const TESTNET_EXPEDITION_TIERS: ITier[] = [
  {
    id: 0,
    name: 'Rookie Hunter',
    title: 'Tier 1 - Rookie Hunter',
    description: 'Start your journey. Build comfort and set the stage for success.',
    milestones: rookie_hunter_milestones,
    totalPoints: rookie_hunter_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/testnet/lg-standard.png',
    badgeBackground: '/imgs/png/expedition/testnet/bg-standard.png',
    borderGradient: 'linear-gradient(180deg, #BEA393 0%, #201C1A 100%)',
    tagIcon: '/imgs/png/expedition/testnet/standard.svg',
    unlocked: true,
  },
  {
    id: 1,
    name: 'Funding Farmer',
    title: 'Tier 2 - Funding Farmer',
    description: 'Engage with the community and grow your presence.',
    milestones: funding_farmer_milestones,
    totalPoints: funding_farmer_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/testnet/lg-silver.png',
    badgeBackground: '/imgs/png/expedition/testnet/bg-silver.png',
    borderGradient: 'linear-gradient(180deg, #C7CDD0 0%, #212526 100%)',
    tagIcon: '/imgs/png/expedition/testnet/silver.svg',
    unlocked: true,
  },
  {
    id: 2,
    name: 'Leverage Pilot',
    title: 'Tier 3 - Leverage Pilot',
    description: 'Engage with the community and grow your presence.',
    milestones: leverage_pilot_milestones,
    totalPoints: leverage_pilot_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/testnet/lg-gold.png',
    badgeBackground: '/imgs/png/expedition/testnet/bg-gold.png',
    borderGradient: 'linear-gradient(180deg, #EEE8D4 0%, #201F1D 100%)',
    tagIcon: '/imgs/png/expedition/testnet/gold.svg',
    unlocked: true,
  },
  {
    id: 3,
    name: 'Volatility Surfer',
    title: 'Tier 4 - Volatility Surfer',
    description: 'Engage with the community and grow your presence.',
    milestones: volatility_surfer_milestones,
    totalPoints: volatility_surfer_milestones.reduce((sum, m) => sum + m.points, 0),
    badgeIcon: '/imgs/png/expedition/testnet/lg-platinum.png',
    badgeBackground: '/imgs/png/expedition/testnet/bg-platinum.png',
    borderGradient: 'linear-gradient(180deg, #EDEAE0 0%, #2E2E2B 100%)',
    tagIcon: '/imgs/png/expedition/testnet/mini-platinum.png',
    unlocked: true,
  },
];
